apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::602898051042:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MV3L0EJU692G
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::602898051042:role/UdacityFlaskDeployCBKubectlRole
      username: build 
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-02T02:55:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1606"
  uid: b494bd39-a171-416f-9832-b823d366ae8a
